qiskit-community/qiskit-optimization

- qiskit_optimization/problems/quadratic_program.py
- test/test_quadratic_program.py
Fixes https://github.com/Qiskit/qiskit-aqua/issues/1462
Copy of https://github.com/Qiskit/qiskit-aqua/pull/1507
This PR moves `keys` argument first to match with [docplex interface](http://ibmdecisionoptimization.github.io/docplex-doc/mp/docplex.mp.model.html?highlight=solve_details#docplex.mp.model.Model.binary_var_dict). `keys` should be given explicitly because the methods are to generate multiple variables at once. `keys=None` does not make sense.
These methods are introduced only in master of Aqua and not yet included in the released version.
> Fix batch variable generation

- qiskit_optimization/applications/ising/docplex.py
- qiskit_optimization/problems/quadratic_program.py
- requirements.txt
- setup.py
Fixes #21
I tested both docplex 2.20.204 and docplex 2.19.202 with test_quadratic_program.py
> Fix for docplex 2.20

- qiskit_optimization/applications/ising/docplex.py
- qiskit_optimization/problems/quadratic_program.py
- requirements.txt
- setup.py
Follow-up of #22 
I replaced `mp.linear.Var` with `mp.dvar.Var` to be compatible with the latest docplex 2.20.204.
`mp.linear.Var` was used until 2.15.194. So, I modified the code to work with both styles.
I add a version pin docplex==2.15.194 for macOS because docplex does not work without cplex on macOS.
See #24 for details.
> Deal with both old and new locations of Var of docplex

- requirements.txt
Decorator had a backward compatibility problem that was affecting networkx for 2 days but the intermediate buggy versions were yanked and a fix was released.
In the meantime, I had added a pin to decorator in requirements.txt in order to publish our docs which is unnecessary now. I am reverting to as it used to be.
> Remove decorator from requirements, added during its buggy period

- requirements.txt
* Remove decorator dependency and restore previous networkx min.requirements
Cherry-pick of #71
> [Stable] Remove decorator from requirements, added during its buggy period

- .github/actions/install-master-dependencies/action.yml
Conan downloads dependencies from JFrog Bintray that goes down sometimes. This disables Conan and installs dependencies in the CI.
> Disable Conan on CI Aer build

- qiskit_optimization/algorithms/grover_optimizer.py
- test/algorithms/test_grover_optimizer.py
Fixes #88 
As mentioned in #88, somehow, we get the different results even with the same seed. This issue didn't occur before. 
I used a different example for the unit test and I get the same result in that case.
> Fix unit test of GroverOptimizer

- qiskit_optimization/algorithms/grover_optimizer.py
- releasenotes/notes/fix-grover-rotation-count-853baefc6b7e8476.yaml
- test/algorithms/test_grover_optimizer.py
Fixes #129
GroverOptimizer's rotation_count is set in a wrong way.
It is originally `rotation_count = int(np.ceil(algorithm_globals.random.uniform(0, m - 1)))`, but it is always 1 if `m=1`.
It should be either 0 or 1. So, I replace it with `algorithm_globals.random.integers(0, m)`.
The order of `result.get_counts(qc)` has an issue. It is sorted by probability, but some bitstrings may have the same probabilities and it results in a probabilistic behavior of unit tests on different environment (mac and linux).
This PR sorts the counts by bitstring order if qasm_simulator is used. So, the resulting iterator has the same order in any environment.
If statevector_simulator is used, it omits the sort because the results are generated in a sorted order.
> Fix GroverOptimizer's rotation_count

- .pylintdict
- qiskit_optimization/algorithms/grover_optimizer.py
- qiskit_optimization/algorithms/optimization_algorithm.py
- qiskit_optimization/problems/quadratic_program.py
- releasenotes/notes/fix-bit-ordering-e807ec9f4b206ec3.yaml
- releasenotes/notes/fix-grover-rotation-count-853baefc6b7e8476.yaml
- test/algorithms/test_grover_optimizer.py
- test/algorithms/test_min_eigen_optimizer.py
Backport #97 #132 to stable
Closes #129
Closes #135
> [Stable] Backport #97 and #132 to stable

- test/algorithms/test_min_eigen_optimizer.py
Due to https://github.com/Qiskit/qiskit-terra/pull/6396, test_samples_qaoa fails.
https://github.com/Qiskit/qiskit-optimization/runs/2588572261
https://github.com/Qiskit/qiskit-terra/issues/6424 explains some details.
This PR adjust the random seed to pass the unit test.
> Adjust random_seed for test_samples_qaoa

- docs/Makefile
- tools/generate_spell_dict.py
Running sphinx spelling and sphinx html together may fail if the previous _build and stubs output is not removed.
> Remove _build & stubs dir before running sphinx

- requirements-dev.txt
Mypy 0.900, released recently, requires `types-dataclasses`. Mypy shows the following message with Python 3.6.
This PR fixes requirements.txt.
```
qiskit_optimization/algorithms/optimization_algorithm.py:16: error: Library stubs not installed for "dataclasses" (or incompatible with Python 3.6)
qiskit_optimization/algorithms/optimization_algorithm.py:16: note: Hint: "python3 -m pip install types-dataclasses"
qiskit_optimization/algorithms/optimization_algorithm.py:16: note: (or run "mypy --install-types" to install all missing stub packages)
qiskit_optimization/algorithms/optimization_algorithm.py:16: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```
> Add types-dataclasses for mypy-0.900

- qiskit_optimization/translators/docplex_mp.py
- releasenotes/notes/add-indicator-constraint-071b54d9ae1b042f.yaml
- test/problems/test_quadratic_program.py
- test/translators/test_docplex_mp.py
Adds support of indicator constraints in `from_docplex_mp`.
This implementation is based on #151.
Fixes #13
Closes #151
> Add indicator constraint support in `from_docplex_mp` translator

- qiskit_optimization/algorithms/admm_optimizer.py
- qiskit_optimization/algorithms/grover_optimizer.py
- qiskit_optimization/algorithms/minimum_eigen_optimizer.py
- qiskit_optimization/algorithms/optimization_algorithm.py
- qiskit_optimization/applications/optimization_application.py
- qiskit_optimization/converters/flip_problem_sense.py
- qiskit_optimization/converters/inequality_to_equality.py
- qiskit_optimization/converters/integer_to_binary.py
- qiskit_optimization/converters/linear_equality_to_penalty.py
- qiskit_optimization/converters/quadratic_program_to_qubo.py
- qiskit_optimization/problems/quadratic_objective.py
- releasenotes/notes/min-eigen-opt-order-9e030bb2d8d63656.yaml
- Changed `MinimumEigenOptimizer` to return the best solution in terms of the original problem. See details.
- Simplified `MinimumEigenOptimizer` and `QuadraticProgramToQubo`
- Removed unnecessary deepcopy in converters
- Revised type hints
- Replace error messages with f-strings
Note: need to address  #175 to pass CI
The current implementation `MinimumEigenOptimizer` returns the best solution `raw_samples[0].x` among `raw_samples` in terms of QUBO as `MinimumEigenOptimizationResult.x`. But, it is not always the best solution in terms of the original problem because inequality constraints are converted into penalties as part of QUBO. So, I changed `MinimumEigenOptimizer` to return the best solution in terms of the original problem as `MinimumEigenOptimizationResult.x`.
> Refactor converters and `MinimumEigenOptimizer`

- qiskit_optimization/converters/linear_equality_to_penalty.py
- test/converters/test_converters.py
I simplified the penalty term of `LinearEqualityToPenalty` in #174.
But, @a-matsuo told me that it is oversimplified https://github.com/Qiskit/qiskit-optimization/pull/157#discussion_r659453113.
I revert `_should_define_penalty` so that `LinearEqualityToPenalty._auto_define_penalty` is invoked even if `LinearEqualityToPenalty` is reused for other optimization problems.
The details are in #34.
> Revert `_should_define_penalty` of `LinearEqualityToPenalty`

- qiskit_optimization/algorithms/warm_start_qaoa_optimizer.py
Pylint 2.9.0 is released today. This PR fixes the following warning raised by pylint 2.9.0.
```
************* Module qiskit_optimization.algorithms.warm_start_qaoa_optimizer
qiskit_optimization/algorithms/warm_start_qaoa_optimizer.py:95:8: C0206: Consider iterating with .items() (consider-using-dict-items)
```
> Fix a warning by pylint 2.9.0

- qiskit_optimization/__init__.py
- qiskit_optimization/problems/quadratic_program.py
Fixed several typos found on `QuadraticProgram` class.
- In the docstring of the `integer_var_list` function, "Uses 'var_list' to construct a dictionary of integer variables" was changed to "Uses 'var_list' to construct a list of integer variables".
- Docstring for `from_ising` function said "Else, x^2 is treat as a quadratic term". Here, "treat" was changed to "treated".
- In `__init__.py`, "Quadratic Unconstrained Binary Optimization (QUBO)" was missing the opening parenthesis.
These typos were found while working on the localization project.
> Fixed typos

- qiskit_optimization/runtime/vqe_program.py
- test/algorithms/test_min_eigen_optimizer.py
> Override classmethod supports_aux_operators in VQEProgram

- qiskit_optimization/converters/integer_to_binary.py
- releasenotes/notes/fix-int2bin-a998f31885d3b9d8.yaml
- test/converters/test_converters.py
This PR fixes two issues of `IntegerToBinary`.
First issue is #227. As discussed with @wpoxon-qci in #228, I adopted this solution https://github.com/Qiskit/qiskit-optimization/issues/228#issuecomment-902022517.
Second issue is about quadratic terms. See the coefficient of the linear term "x@1" in the following example. Note that `x` is represented as `x = 10 + x@0 + 2 * x@1`.
Example
```python
from qiskit_optimization.problems import QuadraticProgram
from qiskit_optimization.converters import IntegerToBinary
qp = QuadraticProgram()
qp.integer_var(10, 13, 'x')
qp.minimize(quadratic={('x', 'x'): 2})
qp2 = IntegerToBinary().convert(qp)
print(qp2)
```
main branch result:
```
\ This file has been generated by DOcplex
\ ENCODING=ISO-8859-1
\Problem name: CPLEX
Minimize
obj: 40 x@0 + 40 x@1 + [ …
```
> Fix `IntegerToBinary` converter with quadratic terms and zero range variables

- qiskit_optimization/runtime/vqe_program.py
Add a check for the type of data expected in the callback wraper in VQEProgram.
This will allow us to close Qiskit-Partners/qiskit-runtime#38
Anticipating changes in the Qiskit Runtime API which will start emitting final results in the WebSocket stream. When that happens, if we don't duck-type in the VQE callback wrapper receiving the interim results, it will get a ValueError exception.
Already done in Qiskit/qiskit-nature#350
> Duck-type VQE interim results

- docs/tutorials/02_converters_for_quadratic_programs.ipynb
I have made some grammar fixes and a few stylistic changes to the text in `docs/tutorials/02_converters_for_quadratic_programs.ipynb`.
- I have also added a link to the [QUBO Wikipedia page](https://en.wikipedia.org/wiki/Quadratic_unconstrained_binary_optimization).
- Most notably, I replaced the phrase `qiskit.aqua.operators` with `qiskit.opflow`.
> Perform minor updates to tutorials/02_converters_for_quadratic_programs

- .mailmap
This adds my personal email address to `.mailmap`~~, so that my name will no longer appear in both forms in `Qiskit.bib`~~.
~~I figured out why [both forms of my name now appear in `Qiskit.bib`](https://github.com/Qiskit/qiskit/pull/1373#issuecomment-991414722).~~  Even though I used my work email address when creating commits for all pull requests I submitted to qiskit-optimization, those that were merged using mergify[bot] (#292 and #293) were rewritten to use my personal email address, presumably because it is the primary address on my GitHub account.  (Nevertheless, I consider this to be a bug in mergify[bot].)  The ones that were merged manually (#295, #296) have my work email address, as expected.
EDIT: Actually, it looks like #295 was merged by mergify[bot], too.  I am not sure why …
> Add garrison's personal email address to .mailmap

- qiskit_optimization/problems/quadratic_program.py
- qiskit_optimization/translators/ising.py
This replaces `Union[OperatorBase, PauliSumOp]` with `OperatorBase`, as `PauliSumOp` is a subclass of `OperatorBase`, so the union is redundant.
I'm proposing this change because I found the union misleading -- I expected that its presence implied that `PauliSumOp` is not part of the `OperatorBase` hierarchy, but that is wrong.  I believe this change makes more sense, but if there is a reason to prefer that `PauliSumOp` be listed explicitly in the `Union`, I am open to learning why.
> Remove unnecessary Union with PauliSumOp

- docs/tutorials/02_converters_for_quadratic_programs.ipynb
I've added the remaining converters to the tutorial and standardized usage in a few places.  I was motivated to formulate a PR when I realized that `LinearInequalityToPenalty` is not the same thing as `LinearEqualityToPenalty` (it was added later, in #157).
Per https://github.com/Qiskit/qiskit-optimization/issues/84#issuecomment-1008211844, I'm not sure if it matters the order in which the converters that `QuadraticProgramToQubo` wraps are listed.
> Mention the remaining converters in the converters tutorial

- qiskit_optimization/algorithms/admm_optimizer.py
This fixes a docstring
I noticed this incorrect docstring and then looked at the `get_compatibility_msg` docstrings in all the other `algorithms` as well, but in the end this was the only incorrect one.
> Correct the `ADMMOptimizer.get_compatibility_msg` docstring

- .github/workflows/main.yml
- pyproject.toml
- releasenotes/notes/add-python310-support-49aa9931cd4dabab.yaml
- setup.py
- tox.ini
Following Qiskit/qiskit-terra#7102
Fixes #319
Fixes #321
There isn't cplex for python 3.10. Keeping the tutorials running under python 3.7 and 3.8
Even though docplex builds and installs on python 3.10, it is not advertised as working in neither python 3.9 nor python 3.10.
The tutorials under python 3.10 fail on docplex. I am keeping the tutorials CI running for python 3.7 and python 3.8 as before.
The failure occurs inside `08_cvar_optimization.ipynb`:
```
mdl = Model("portfolio_optimization")
x = mdl.binary_var_list("x{}".format(i) for i in range(n))
objective = mdl.sum([mu[i] * x[i] for i in range(n)])
objective -= q * mdl.sum([sigma[i, j] * x[i] * x[j] for i in range(n) for j in range(n)])
mdl.maximize(objective)
mdl.add_constraint(mdl.sum(x[i] for i in range(n)) == budget)
qp = …
```
> Add support for Python 3.10

- qiskit_optimization/translators/ising.py
When referring someone to the `to_ising` method I noticed that the args were not documented and the return was not well formatted. 
- - - - - -
This PR adds the Args and fixes the return so it now looks like this
> Fix up to_ising docstring

- qiskit_optimization/algorithms/cplex_optimizer.py
- qiskit_optimization/algorithms/goemans_williamson_optimizer.py
- qiskit_optimization/algorithms/gurobi_optimizer.py
- qiskit_optimization/applications/bin_packing.py
- qiskit_optimization/applications/graph_optimization_application.py
- qiskit_optimization/optionals.py
- qiskit_optimization/problems/quadratic_program.py
- qiskit_optimization/translators/gurobipy.py
- requirements.txt
- test/__init__.py
- test/algorithms/test_cplex_optimizer.py
- test/algorithms/test_goemans_williamson_optimizer.py
- test/algorithms/test_gurobi_optimizer.py
- test/algorithms/test_min_eigen_optimizer.py
- test/algorithms/test_recursive_optimization.py
- test/algorithms/test_warm_start_qaoa.py
- test/applications/test_bin_packing.py
- test/applications/test_max_cut.py
- test/converters/test_converters.py
- test/optimization_test_case.py
- test/problems/test_quadratic_program.py
- test/translators/test_gurobi.py
Adopt the API implemented in Qiskit/qiskit-terra#7525
> Adopt lazy imports from Terra

- qiskit_optimization/algorithms/recursive_minimum_eigen_optimizer.py
The code example was passing a ``QAOA`` as ``optimizer``
but this needs to be an ``OptimizationAlgorithm``.
Also, the formatting for the reference was adjusted. Using a colon
starts a new subsection in Sphinx, which we don't want here:
> Fix code example in ``RecursiveMinimumEigenOptimizer``

- qiskit_optimization/algorithms/grover_optimizer.py
- releasenotes/notes/basebackend-d32c42427b434739.yaml
> Remove legacy providers interface

- qiskit_optimization/translators/ising.py
- releasenotes/notes/fix-ising-9f8803b8a7a7e78b.yaml
- test/translators/test_ising.py
- Fixes an issue that `from_ising` raises an error with Pauli I.
- Fixes an issue that `to_ising` returns a wrong operator with an input problem without any variable.
Fixes #354
Replaced `assert_array_almost_equal` with `assert_allclose` in test_ising.py following [numpy's doc](https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_array_almost_equal.html).
> It is recommended to use one of [assert_allclose](https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_allclose.html#numpy.testing.assert_allclose), [assert_array_almost_equal_nulp](https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_array_almost_equal_nulp.html#numpy.testing.assert_array_almost_equal_nulp) or [assert_array_max_ulp](https://numpy.org/doc/stable/reference/generated/nump …
> Fix `from_ising` with identity terms

- test/algorithms/test_grover_optimizer.py
Aer is in the process of migrating out of namespaces.
In the meantime, `from qiskit import Aer` emits a deprecation asking to use qiskit_aer which is not ready yet.
Using `qiskit.providers.aer` works fine but it is giving pylint errors when statically loading.
Until qiskit-aer has its own root package qiskit_aer, I am importing Aer dynamically under unit tests to avoid pylint errors.
> Load Aer dynamically in unit tests

- .github/workflows/main.yml
After Terra Qiskit/qiskit-terra#8737 fix, reinstate tests without matplotlib installed.
> Reinstate removal of matplotlib in CI unit tests

- qiskit_optimization/algorithms/minimum_eigen_optimizer.py
- test/algorithms/test_min_eigen_optimizer.py
This PR has `MinimumEigenOptimizer` raises an error if the new `VQE` is given because `MinimumEigenOptimizer` supports `SamplingVQE` instead.
I added a special error message to suggest `SamplingVQE` if `VQE` is given because it can often happen.
> Raise an error if `VQE` is given to `MinimumEigenOptimizer`

- qiskit_optimization/algorithms/grover_optimizer.py
- qiskit_optimization/algorithms/optimization_algorithm.py
- test/algorithms/test_grover_optimizer.py
Simplified Sampler code for `GroverOptimizer` by interpreting quasi distribution  with `binary_probabilities` method.
- Introduces `min_probability` 1e-6 same as `OptimizationAlgorithm._eigenvector_to_solutions`. I want to discuss the parameter `min_probability` at #449.
https://github.com/Qiskit/qiskit-optimization/blob/e9751cbc8bd082202a1c017b6264db0af2235e84/qiskit_optimization/algorithms/optimization_algorithm.py#L525
- Uses `AerSampler` instead of the reference Terra `Sampler` because `AerSampler` is much faster than the reference `Sampler` as follows.
- Removed a warning message that users cannot control https://github.com/Qiskit/qiskit-optimization/pull/448#discussion_r1036216409
main
```
> python -m unittest test.algorithms.test_grover_optimizer.TestGroverOptimizer.test_samples_and …
```
> Update `GroverOptimizer` with Sampler

- requirements.txt
Qiskit optimization requires Terra 0.22.4 that includes various fixes of sampling-based algorithms https://github.com/Qiskit/qiskit-terra/releases/tag/0.22.4 to run the tutorials properly.
> Update the minimum version of Qiskit Terra

- .github/CODEOWNERS
- .github/workflows/deploy-docs.yml
Removes Manoel from both, adds Imamichi-san to deploy docs users allowed to run it.
> Update deploy docs workflow and codeowners

- .pylintdict
- qiskit_optimization/runtime/vqe_client.py
- releasenotes/notes/runtimeclient-v2compat-c5b5541401cc6405.yaml
- test/algorithms/test_min_eigen_optimizer.py
Adds support for ``BackendV2`` backends in the runtime clients.
This is the analogous PR to Qiskit/qiskit-nature#1116.
> Fix ``BackendV2`` support in runtime clients

- docs/conf.py
- requirements-dev.txt
- tox.ini
See Qiskit/qiskit-nature#1109 for more detail.
Basically does the same three things
- Removes dependency on sphinx-autodoc-typehints
- Adds default thumbnail config as that changed in nbsphinx 0.9
- Updates tox.ini gettext section used for translatable strings due to ipykernel not being installed by default now
> Various docs changes for CI

- docs/tutorials/06_examples_max_cut_and_tsp.ipynb
- docs/tutorials/07_examples_vehicle_routing.ipynb
- docs/tutorials/08_cvar_optimization.ipynb
- docs/tutorials/09_application_classes.ipynb
- docs/tutorials/10_warm_start_qaoa.ipynb
- docs/tutorials/12_qaoa_runtime.ipynb
After update the conf.py, like the other repos, to list the default thumbnail image. since with nbsphinx 0.9 it no longer recognizes the older way of doing that with the png file, some tiles "lost" their images, as below. Only the 5 with explicit images in the conf.py show up
This is how it looked before without the conf/py default thumbnail change where the tile that should have the sphere image does not.
It seems that the last image in the notebook was automatically selected how things were before. I added an explicit `nbsphinx-thumbnail` tag to the respective cell (as we have done in other repos which is why I did not see that there). I also selected a better image, I think, for the qaoa runtime. This is how it looks now.
> Tag cell with nbsphinx-thumbnail

- docs/tutorials/12_qaoa_runtime.ipynb
- qiskit_optimization/runtime/__init__.py
- qiskit_optimization/runtime/qaoa_client.py
- qiskit_optimization/runtime/vqe_client.py
- releasenotes/notes/deprecate-vqe-client-de93fff8c4645802.yaml
- test/runtime/test_qaoaclient.py
- test/runtime/test_vqeclient.py
`VQEClient` and `QAOAClient` are superseded by the Qiskit Runtime Primitives.
This PR follows https://github.com/Qiskit/qiskit-nature/pull/1124.
I noticed that #441 accidentally removed unit tests of `VQEClient` and `QAOAClient`. So, I restored them.
Fixes #494
> Deprecate `qiskit_optimization.runtime` module

- .github/workflows/main.yml
Most people agree that GitHub made a mistake by having forks run CI both on the fork and in the upstream repository. It wastes computing resources (which has a real environmental cost!).
If people really want to run CI in their fork, they can always modify their fork's config to revert this change.
> Turn off CI for forks

- docs/_templates/autosummary/class_no_inherited_members.rst
This is similar to Qiskit/qiskit-machine-learning#635 (and the equivalent done in Nature).
Basically it alters the class template to show inherited methods so that this is now default. I debated, as it's not needed here, at least for now, but I also added the original class template, for consistency with the other repos, as class_no_inherited_methods (named same as qiskit-terra) so that  this template can be used explicitly for autosummary where we do not want inherited methods (in the other app repos this is used for circuit.library circuits, such as UCC, RawFeatureVector).
> Improve docs

- releasenotes/notes/add-python311-support-b44aa96b718e7914.yaml
- setup.py
There was a new [Cplex release 22.1.1.1](https://pypi.org/project/cplex/22.1.1.1/#files) which added wheels for Python 3.11. This PR simply removes the version restriction from setup.py. Since the 3,11 support overall of Qiskit Optimization has not yet been released this did not need any reno, but I did update the reno from the 3.11 PR to remove the note above CPLEX not supporting 3.11.
> Remove Cplex 3.11 restriction now that Cplex supports it

- .github/workflows/deploy-code.yml
- .github/workflows/main.yml
- pyproject.toml
- releasenotes/notes/drop_python_37-c640811d7c84520e.yaml
- setup.py
- tox.ini
Qiskit has dropped support Python 3.7 and this follows suit for Qiskit Optimization.
follows https://github.com/qiskit-community/qiskit-finance/pull/288
depends on #536
> Drop python 3.7 support

- test/algorithms/test_admm.py
A unit test error occurs for test_admm_ex5_warm_start because the optimal solution is not unique and some algorithms behave in a differently on Apple silicon maybe due to blas stuff.
The optimization problem is as follows.
```python
v = mdl.binary_var(name="v")
w = mdl.binary_var(name="w")
t = mdl.binary_var(name="t")
mdl.minimize(v + w + t)
mdl.add_constraint(2 * v + 2 * w + t <= 3, "cons1")
mdl.add_constraint(v + w + t >= 1, "cons2")
mdl.add_constraint(v + w == 1, "cons3")
```
Due to symmetry of `v` and `w`, both `[0, 1, 0]` and `[1, 0, 0]` are optimal.
There are two options to fix this issue: 1) check two optimal solutions or 2) modify the problem to make `v` and `w` non-symmetry. This PR took the first option because the problem ex5 is cited from a paper.
Fixes #525
The result of …
> Fix a unit test error for Apple silicon

- qiskit_optimization/algorithms/qrao/quantum_random_access_optimizer.py
- qiskit_optimization/algorithms/recursive_minimum_eigen_optimizer.py
- qiskit_optimization/algorithms/scipy_milp_optimizer.py
- qiskit_optimization/optionals.py
- requirements.txt
- test/algorithms/qrao/test_quantum_random_access_optimizer.py
- test/algorithms/test_scipy_milp_optimizer.py
Fix mypy error in main branch.
https://github.com/qiskit-community/qiskit-optimization/actions/runs/6172901069
Also fixes following items
- qiskit.utils -> qiskit_algorithms.utils
- minimum scipy version that supports `ScipyMilpOptimizer`.
> Minor fixes

- constraints.txt
- qiskit_optimization/applications/vehicle_routing.py
- requirements-dev.txt
~~Fix "stestr run" error by pinning python-subunit version.~~
Update stestr version that has been just released.
https://github.com/mtreinish/stestr/releases/tag/4.1.0
Fix mypy by modifying colormap access.
I found these errors in the recent scheduled CI.
https://github.com/qiskit-community/qiskit-optimization/actions/runs/6217275395
> Fix stestr and mypy issues

- qiskit_optimization/applications/bin_packing.py
Fixes a deprecation warning.
https://github.com/qiskit-community/qiskit-optimization/pull/559#issuecomment-1726325288
> qiskit_optimization/applications/bin_packing.py:121: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed two minor releases later. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap(obj)`` instead.
colors = plt.cm.get_cmap("jet", len(self._weights))
> Fix a deprecation warning of matplotlib

- docs/conf.py
- qiskit_optimization/algorithms/__init__.py
- qiskit_optimization/algorithms/qrao/__init__.py
- qiskit_optimization/applications/__init__.py
- qiskit_optimization/converters/__init__.py
- qiskit_optimization/problems/__init__.py
- qiskit_optimization/translators/__init__.py
- requirements-dev.txt
Updates to new Ecosystem theme.
Total file size increased (4.76 MB → 5.36 MB) 
index.html size increased (15 KB → 40.2 KB)
Build time increased (47s → 52s)
For more information: https://github.com/Qiskit/qiskit_sphinx_theme/issues/232
> Updates to new Ecosystem theme.

- .github/actions/install-main-dependencies/action.yml
- .github/actions/install-optimization/action.yml
- .github/actions/run-tests/action.yml
- .github/workflows/main.yml
Changed windows-2019 to windows-latest (current same as windows-2022) so it running on a newer version and use latest like is done on others. My recollection of it using windows-2019 specifically was when Aer was being built from source. As this is no longer the case it seems better to switch to a newer version and do -latest like is done with Ubuntu and Mac
I already did this in Nature https://github.com/qiskit-community/qiskit-nature/pull/1266 as part of updating CI there.
The branch rules will need updating to account for the job name change.
> Update CI to use latest windows

- docs/migration/01_migration_guide_to_v0.5.rst
- docs/migration/02_migration_guide_to_v0.6.rst
- docs/migration/index.rst
- releasenotes/notes/0.6-prelude-2740977b31d22583.yaml
- releasenotes/notes/switch-to-qiskit-algorithms-b0af38fe547bf5b5.yaml
- Added prelude of v0.6.
- Added migration guide to v0.6.
> Add Prelude 0.6

- qiskit_optimization/__init__.py
- qiskit_optimization/infinity.py
Fixes #10 
It now comes out as
with the linked page
It did try with autodata which brings what is in the separate page inline there on the main page. But then it has that yellow stripe across the page which changed things more. I know we have brought all methods onto the same page so maybe that is reasonable to do. But since it changed things more than simply fixing the text of what was there I left it with this more minimal change.
Either as it stands or with autodata it needs the fully qualified path to bring in the comment for the constant - otherwise you still get that `Convert a string or number to a floating point number, if possible.` which is what the docs currently show,
I labelled it backport since we publish docs off stable and maybe we want to update/re-publish the docs with …
> Improve documentation of INFINITY

- qiskit_optimization/translators/gurobipy.py
Scheduled CI fails due to the new [gurobipy 11.0](https://pypi.org/project/gurobipy/11.0.0/) released on Nov 28.
This PR fixes type annotations.
> Fix mypy for gurobipy 11.0

- README.md
- docs/conf.py
- docs/index.rst
- docs/migration/02_migration_guide_to_v0.6.rst
- docs/tutorials/08_cvar_optimization.ipynb
- docs/tutorials/12_quantum_random_access_optimizer.ipynb
- qiskit_optimization/__init__.py
- setup.py
Updates links away from qiskit.org to the new locations for the docs
Fixes #585
Fixes #586
Now that all the applications and the algorithms docs are deployed on github pages this updates the intersphinx links, in conf.py, and also urls that are coded directly in other places such as the readme and tutorials. I did not alter past release notes. There is a redirect now in effect for the former location on `qiskit.org/ecosystem` so they get to the right place.
Note that the current theme is still emitting a link to qiskit.org/ecosystem, but that will get redirected for now until such time as Qiskit/qiskit_sphinx_theme#588 is resolved and new docs are generated with such an updated theme and re-deployed.
> Update intersphinx links and others

- README.md
- docs/getting_started.rst
Updates the version number of Python for which no CPLEX version exists, yet.
In this case, updating from 3.9 to 3.12.
This fixes issue #591.
No more details required.
> Update CPLEX-incompatible Python version in documentation 

- .github/workflows/main.yml
I noticed, when looking at last nights CI, which had failed (was just due to some network issue where it timed out (re-running the job passed) that for Mac and Windows the job is still using Python 3.10. Normally we test these platforms at the lowest and highest Python level supported but perhaps this was kept at 3.10 as sometimes wheels for these, for the latest version of Python, are longer coming. (All other app repos are doing this at 3.8 and 3.11 so this change will bring Opt in to sync in that respect).
Anyway I updated these so Mac and Windows now test at 3.8 and 3.11, instead of 3.8 and 3.10. I would imagine this should all work by now, but can't check locally.
Assuming this passes it will need the branch rules updated accordingly. I labelled it backport since the last release was …
> Bump Mac and Win upper Python version for CI

- docs/tutorials/01_quadratic_program.ipynb
- docs/tutorials/02_converters_for_quadratic_programs.ipynb
- docs/tutorials/03_minimum_eigen_optimizer.ipynb
- docs/tutorials/04_grover_optimizer.ipynb
- docs/tutorials/05_admm_optimizer.ipynb
- docs/tutorials/06_examples_max_cut_and_tsp.ipynb
- docs/tutorials/07_examples_vehicle_routing.ipynb
- docs/tutorials/08_cvar_optimization.ipynb
- docs/tutorials/09_application_classes.ipynb
- docs/tutorials/10_warm_start_qaoa.ipynb
- docs/tutorials/11_using_classical_optimization_solvers_and_models.ipynb
- docs/tutorials/12_quantum_random_access_optimizer.ipynb
- docs/tutorials/tutorial_magics.py
Qiskit 1,0 removed the deprecated qiskit.tools which included some .jupyter from which the magics that did the version and copyright were imported. This PR adds a local file in the tutorials folder that contains just these magics and changes the import to use this.
Similar fix to qiskit-community/qiskit-algorithms#156
I removed an import from qiskit.tools which is now gone - the import did not seem to be used anymore
I also tweaked one of the imports so it does not import direct from the module but just from qiskit_algorithms.utils
I do not expect this to pass until the other failures are sorted. A new release of Qiskit Algorithms is required to work with Qiskit 1.0, but at least its ready.
> Fix tutorials to work with Qiskit 1.0

- .github/workflows/main.yml
- releasenotes/notes/add-python312-support-e3e2bc0c6a10b613.yaml
- setup.py
- tox.ini
Closes #590
Add Python 3.12 support.
But since CPLEX does not support Python 3.12 (see [pypi](https://pypi.org/project/cplex/#files)), we need to add constraint to 'cplex' extra dependency.
Windows and mac are still tested with Python 3.11 because cplex are not available for 3.12.
Fixes #577 
Latest cplex 22.1.1.1
> Add Python 3.12 support

- qiskit_optimization/__init__.py
- requirements.txt
Docplex does not support Numpy version 2 and qiskit-algorithms does not support Scipy 1.14.
So, this PR pin the numpy and scipy versions.
This also fixes a warning of sphinx related to `INFINITY`.
> Pin numpy<2 and scipy<1.14

- .github/workflows/main.yml
`pip check` of CI fails since a couple of days ago.
```
gurobipy 11.0.3 is not supported on this platform
```
I found an issue of pip https://github.com/pypa/pip/issues/12884 is likely to be related to the failure. I try to pin pip only for `pip check`.
> Pin pip for "pip check"

- requirements.txt
- test/algorithms/qrao/test_quantum_random_access_optimizer.py
docplex 2.28.240 was released on Aug 2 with numpy 2 support. So, I unpin the numpy version
https://pypi.org/project/docplex/2.28.240/#history
requires #630 to pass CI
> Unpin numpy

- qiskit_optimization/algorithms/qrao/magic_rounding.py
- releasenotes/notes/fix-qrao-d0402da6a5c40121.yaml
- test/algorithms/qrao/test_magic_rounding.py
Fix ``MagicRounding`` so that the decision variables can be decoded correctly.
Fix #626. 
The iteration order of ``var2op`` in the method, ``_unpack_measurement_outcome`` in :class:`~qiskit_optimization.algorithms.qrao.MagicRounding` has been modified so that it can correctly run in the order of the decision variables.
✅ I have added the tests to cover my changes.
✅ I have updated the documentation accordingly.
✅ I have read the CONTRIBUTING document.
> Fix incorrect decoding of decision variables by ``MagicRounding``

- .pylintrc
- qiskit_optimization/algorithms/admm_optimizer.py
- qiskit_optimization/algorithms/cobyla_optimizer.py
- qiskit_optimization/algorithms/goemans_williamson_optimizer.py
- qiskit_optimization/algorithms/grover_optimizer.py
- qiskit_optimization/algorithms/minimum_eigen_optimizer.py
- qiskit_optimization/algorithms/optimization_algorithm.py
- qiskit_optimization/algorithms/recursive_minimum_eigen_optimizer.py
- qiskit_optimization/algorithms/slsqp_optimizer.py
- qiskit_optimization/algorithms/warm_start_qaoa_optimizer.py
- qiskit_optimization/applications/max_cut.py
- qiskit_optimization/applications/vehicle_routing.py
- qiskit_optimization/problems/linear_constraint.py
- qiskit_optimization/problems/quadratic_constraint.py
- qiskit_optimization/problems/quadratic_objective.py
- qiskit_optimization/problems/quadratic_program.py
- qiskit_optimization/problems/variable.py
- qiskit_optimization/translators/prettyprint.py
This PR fixes the bug in the max-cut solver as reported in https://github.com/qiskit-community/qiskit-optimization/issues/611
> Fix bug in max-cut solver (issue #611)

- requirements.txt
numpy 2.2.0 was released recently and it causes mypy errors as follows.
In order to merge existing PRs, I would like to pin numpy version first.
After we merge all existing PRs, we get back to these mypy errors.
I feel the error does not make sense because `tuple[int, int]` should be matched `tuple[int, ...]`.
```
qiskit_optimization/converters/linear_inequality_to_penalty.py:218: error: Incompatible types in assignment (expression has type "ndarray[tuple[int, ...], dtype[Any]]", variable has type "ndarray[tuple[int, int], dtype[Any]]")  [assignment]
qiskit_optimization/converters/linear_inequality_to_penalty.py:221: error: Incompatible types in assignment (expression has type "ndarray[tuple[int, ...], dtype[Any]]", variable has type "ndarray[tuple[int, int], dtype[Any]]")  [assignment] …
```
> Pin numpy<2.2.0

- docs/conf.py
- docs/getting_started.rst
- docs/migration/01_migration_guide_to_v0.5.rst
- releasenotes/notes/0.5/add-primitives-support-31af39549b5e66e3.yaml
The documentation source of truth is moving to https://quantum.cloud.ibm.com/.
> Update intersphinx mapping and other URLs pointing to IQP Classic
