qiskit-community/qiskit-optimization

- test/test_qaoa.py
This PR fixes and enables a test `test_qaoa_initial_state`.
> Fix test TestQAOA.test_qaoa_initial_state 

- .github/actions/install-master-dependencies/action.yml
- .github/actions/install-optimization/action.yml
- .github/workflows/main.yml
- .mailmap
- CONTRIBUTING.md
- README.md
- qiskit_optimization/__init__.py
- qiskit_optimization/algorithms/minimum_eigen_optimizer.py
- qiskit_optimization/applications/ising/docplex.py
- qiskit_optimization/problems/quadratic_program.py
- qiskit_optimization/version.py
- requirements.txt
- setup.py
- tools/check_copyright.py
- tox.ini
> Updates to readme and remove ignis from requirements

- qiskit_optimization/problems/quadratic_program.py
> Fix mypy errors

- .github/actions/install-libraries/action.yml
- .github/actions/install-optimization/action.yml
- .github/workflows/main.yml
- setup.py
Add cplex 20.1 for Python 3.8.
https://pypi.org/project/cplex/20.1.0.0/#files
> Add cplex for python 3.8

- qiskit_optimization/applications/ising/clique.py
- qiskit_optimization/applications/ising/docplex.py
- qiskit_optimization/applications/ising/exact_cover.py
- qiskit_optimization/applications/ising/graph_partition.py
- qiskit_optimization/applications/ising/knapsack.py
- qiskit_optimization/applications/ising/max_cut.py
- qiskit_optimization/applications/ising/partition.py
- qiskit_optimization/applications/ising/set_packing.py
- qiskit_optimization/applications/ising/stable_set.py
- qiskit_optimization/applications/ising/tsp.py
- qiskit_optimization/applications/ising/vehicle_routing.py
- qiskit_optimization/applications/ising/vertex_cover.py
- qiskit_optimization/problems/quadratic_program.py
- test/test_vehicle_routing.py
> Fix deprecation messages

- README.md
- qiskit_optimization/algorithms/cplex_optimizer.py
- qiskit_optimization/problems/quadratic_program.py
> Improve install msg for extra require packages

- .github/workflows/main.yml
- qiskit_optimization/algorithms/grover_optimizer.py
- qiskit_optimization/applications/ising/common.py
- qiskit_optimization/applications/ising/tsp.py
- setup.py
- test/test_clique.py
- test/test_docplex.py
- test/test_exact_cover.py
- test/test_graph_partition.py
- test/test_grover_optimizer.py
- test/test_min_eigen_optimizer.py
- test/test_partition.py
- test/test_qaoa.py
- test/test_readme_sample.py
- test/test_set_packing.py
- test/test_stable_set.py
- test/test_tsp.py
- test/test_vehicle_routing.py
- test/test_vertex_cover.py
> Change aqua_globals to algorithm_globals

- .github/workflows/main.yml
- qiskit_optimization/algorithms/cobyla_optimizer.py
- qiskit_optimization/algorithms/multistart_optimizer.py
- qiskit_optimization/algorithms/optimization_algorithm.py
- qiskit_optimization/algorithms/slsqp_optimizer.py
- qiskit_optimization/applications/ising/knapsack.py
- qiskit_optimization/applications/ising/vehicle_routing.py
- tox.ini
> Run mypy on python 3.7

- .github/actions/install-master-dependencies/action.yml
- .github/workflows/main.yml
- requirements.txt
- setup.py
> Fix cvxpy CI install error on python 3.7

- qiskit_optimization/algorithms/grover_optimizer.py
- test/test_readme_sample.py
This PR fixes:
- `GroverOptimizer` due to changes introduced in https://github.com/Qiskit/qiskit-terra/pull/5680. Now problem definition is separated from the algorithm.
- `test_readme_sample.py` due to changes introduced in https://github.com/Qiskit/qiskit-terra/pull/5678. The `p` parameter renamed to `reps`.
> Fix GroverOptimizer and tests to accomodate recent changes in Terra

- .github/workflows/main.yml
Tutorials fail randomly due to Jupyter bug: jupyter/jupyter_client#541
This PR disables parallelism on tutorials by setting env: QISKIT_PARALLEL=False
> Disable parallelism on tutorials job

- .pylintdict
- constraints.txt
- requirements-dev.txt
- requirements.txt
- setup.py
Upgrades pylint minimum version following Qiskit/qiskit-terra#5630
Updates constraints.txt, requirements.txt to be equivalent to qiskit-terra
> Upgrade to pylint 2.7

- .pylintdict
- qiskit_optimization/algorithms/minimum_eigen_optimizer.py
- qiskit_optimization/algorithms/optimization_algorithm.py
- qiskit_optimization/algorithms/recursive_minimum_eigen_optimizer.py
- test/algorithms/test_recursive_optimization.py
Since we have introduced `samples` property in the `OptimizationResult` we can make `RecursiveMinimumEigenOptimizer` more generic and accept wider range of optimizers. This is what is done in this PR.
> Updated recursive optimizer

- qiskit_optimization/algorithms/minimum_eigen_optimizer.py
- qiskit_optimization/algorithms/optimization_algorithm.py
- qiskit_optimization/applications/tsp.py
> Fix QiskitOptimizationError import path

- MANIFEST.in
- setup.py
Manifest was missing including *.txt file at top and setup.py was not including top files.
> Fix Setup and Manifest

- qiskit_optimization/applications/vehicle_routing.py
- test/applications/test_clique.py
- test/applications/test_vehicle_routing.py
Fixed a bug in vehicle_routing,  while added a test case for the fix, another test case for vehicle_routing, and a test case for clique.
Fixed a bug in the 'interpret' function of vehicle_routing, which caused the right solution not to be produced when the node index for the depot is not the default value. 
Added a test case for vehicle_routing in which the depot is not the default value, and another test case in which the number_of vehicles is not the default value. 
Also added a test case for clique in which the clique size is specified.
> Fixed a bug in vehicle_routing, and added test cases for vehicle_routing and for clique. 

- setup.py
> Change setup.py setuptools from find_namespace_packages to find_packages

- docs/tutorials/06_examples_max_cut_and_tsp.ipynb
copy https://github.com/Qiskit/qiskit-tutorials/pull/1152
> Fix math mode of tutorial

- .github/actions/install-main-dependencies/action.yml
- .github/workflows/main.yml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- docs/tutorials/07_examples_vehicle_routing.ipynb
- qiskit_optimization/version.py
- tox.ini
Related to Qiskit/qiskit-terra#6221
More details at: https://github.com/github/renaming
Forks should also rename the default branch from master to main in Github settings.
After renaming your fork in Github, you should issue the following commands locally:
```
git checkout master
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
git remote prune origin
```
> Prepare for renaming default branch to main

- README.md
Updated README file to show example with correct arguments in two functions.
> Updated example in README file

- .github/workflows/main.yml
> [Stable] Make sure CI gets Qiskit dependencies from pypi on stable (#85)

- .github/actions/install-main-dependencies/action.yml
- .github/workflows/main.yml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- docs/tutorials/07_examples_vehicle_routing.ipynb
- qiskit_optimization/version.py
- tox.ini
* Prepare for renaming default branch to main
Backport of #89
> [Stable] Prepare for renaming default branch to main (#89)

- qiskit_optimization/version.py
- test/problems/test_quadratic_program.py
- tools/check_copyright.py
Latest pylint release introduced new test that are causing the CI to fail on main and stable.
> Fix lint msgs caused by latest pylint release

- .github/actions/run-tests/action.yml
- .github/workflows/main.yml
- test/__init__.py
- test/algorithms/test_cplex_optimizer.py
- test/algorithms/test_goemans_williamson_optimizer.py
- test/algorithms/test_min_eigen_optimizer.py
- test/algorithms/test_recursive_optimization.py
- test/algorithms/test_warm_start_qaoa.py
- test/converters/test_converters.py
- test/optimization_test_case.py
- test/problems/test_quadratic_program.py
> Add 'run_slow' handling and requires_extra_library unit test decorator

- .github/actions/run-tests/action.yml
- .github/workflows/main.yml
- test/__init__.py
- test/algorithms/test_cplex_optimizer.py
- test/algorithms/test_goemans_williamson_optimizer.py
- test/algorithms/test_min_eigen_optimizer.py
- test/algorithms/test_recursive_optimization.py
- test/algorithms/test_warm_start_qaoa.py
- test/converters/test_converters.py
- test/optimization_test_case.py
- test/problems/test_quadratic_program.py
> [Stable] Add 'run_slow' handling and requires_extra_library unit test decorator (#104)

- .github/actions/run-tests/action.yml
- .github/workflows/main.yml
>  Print PendingDeprecation warnings in the CI

- .github/workflows/deploy-docs.yml
- .github/workflows/main.yml
> [Stable] Fix sphinx CI Error (#121)

- .github/workflows/deploy-docs.yml
- .github/workflows/main.yml
- requirements-dev.txt
Copy https://github.com/Qiskit/qiskit-nature/pull/187
> Pin sphinx version below 4.0.0

- .github/workflows/deploy-docs.yml
- .github/workflows/main.yml
> Remove redundant installs from CI 

- .github/workflows/deploy-docs.yml
- .github/workflows/main.yml
- requirements-dev.txt
> [Stable] Pin Sphinx version below 4.0.0

- qiskit_optimization/algorithms/cplex_optimizer.py
- releasenotes/notes/add-cplex-params-2b7bd7bde01400c7.yaml
- test/algorithms/test_cplex_optimizer.py
Simplifies `CplexOptimizer` by directly calling `docplex.mp.model.Model.solve`.
Adds `cplex_parameters` to set various CPLEX options.
Fixes #133
> Revise CplexOptimizer

- README.md
- docs/conf.py
- docs/custom_directives.py
- docs/getting_started.rst
- docs/index.rst
- requirements-dev.txt
> Add Getting Started Documentation

- docs/tutorials/06_examples_max_cut_and_tsp.ipynb
- docs/tutorials/08_cvar_optimization.ipynb
- test/algorithms/test_grover_optimizer.py
> Remove Backend Deprecate Messages

- README.md
The bib file link in the readme returned a "Page not found" error. This PR fixes it.
> Fixed link to bib file in README

- requirements.txt
Update docplex version to 2.21.207.
Fixes #24
> Update docplex version

- qiskit_optimization/converters/quadratic_program_converter.py
- test/problems/test_quadratic_program.py
> Fix unused imports

- qiskit_optimization/algorithms/cplex_optimizer.py
- qiskit_optimization/algorithms/gurobi_optimizer.py
- qiskit_optimization/algorithms/recursive_minimum_eigen_optimizer.py
- qiskit_optimization/algorithms/slsqp_optimizer.py
- qiskit_optimization/converters/inequality_to_equality.py
- qiskit_optimization/converters/integer_to_binary.py
- test/algorithms/test_cobyla_optimizer.py
- test/converters/test_converters.py
> Remove unused logger

- qiskit_optimization/algorithms/admm_optimizer.py
- qiskit_optimization/deprecation.py
- qiskit_optimization/problems/quadratic_program.py
- test/algorithms/test_admm.py
- test/problems/test_quadratic_program.py
- test/test_deprecation.py
- test/translators/test_gurobi.py
It adds common method to be used in deprecated messages in order to make them standard.
> Add deprecation method template

- docs/apidocs/qiskit_optimization.translators.rst
- qiskit_optimization/__init__.py
- qiskit_optimization/problems/quadratic_program.py
- qiskit_optimization/translators/docplex_mp.py
- qiskit_optimization/translators/gurobipy.py
Remove TYPE_CHECKING and add QuadraticProgram to typehints.
Add translators to docs
> Remove TYPE_CHECKING flag from code

- .pylintdict
- qiskit_optimization/deprecation.py
- test/test_deprecation.py
New Deprecate Enum and deprecate_property
Improvements to deprecation unit tests
> Improvements to deprecate methods

- qiskit_optimization/algorithms/admm_optimizer.py
Fixes #175 
I looked for a solution of the mypy error, but I could not find one.
I welcome better solutions.
> Add type ignore for numpy 1.21

- qiskit_optimization/algorithms/gurobi_optimizer.py
- qiskit_optimization/translators/gurobipy.py
- test/translators/test_gurobi.py
- Removed unnecessary `gurobipy.Model.optimize()` in test_gurobi.py
- Added a missing model update in `to_gurobipy`
- Suppress the following message of parameter change in `GurobiOptimizer` if `disp` is False. 
```
Changed value of parameter NonConvex to 2
Prev: -1  Min: -1  Max: 2  Default: -1
```
> Suppress Gurobi message when `disp==False` and add the missing model update

- .pylintdict
- qiskit_optimization/problems/quadratic_program.py
- qiskit_optimization/problems/substitute_variables.py
- test/algorithms/test_warm_start_qaoa.py
- test/problems/test_quadratic_program.py
- test/problems/test_substitute_variables.py
Separeted `SubstituteVariable` out from `QuadraticProgram` to simplify the very long code of `QuadraticProgram`.
> Separate `SubstituteVariable` out from `QuadraticProgram`

- .github/workflows/main.yml
- .pylintdict
- .pylintrc
- Makefile
- qiskit_optimization/deprecation.py
- requirements-dev.txt
- test/test_deprecation.py
- tools/verify_headers.py
- tox.ini
Equivalent to Qiskit/qiskit-nature#251
> Move away from using pylint header plugin & new deprecate_values decorator

- docs/getting_started.rst
Changed "qiskit[optimizationg]" to "qiskit[optimization]" in getting started file.
> Getting started: fix typo

- qiskit_optimization/algorithms/cplex_optimizer.py
- releasenotes/notes/add-cplex-params-2b7bd7bde01400c7.yaml
- releasenotes/notes/add-gurobipy-94f45e32abb61c7b.yaml
- releasenotes/notes/add-indicator-constraint-071b54d9ae1b042f.yaml
- releasenotes/notes/add-ising-translator-b93e22adda321e56.yaml
- releasenotes/notes/add-model-translators-11e7f3b53574afa7.yaml
- releasenotes/notes/fix-bit-ordering-e807ec9f4b206ec3.yaml
- releasenotes/notes/fix-empty-obj-3a99dc67c319806d.yaml
- releasenotes/notes/fix-grover-rotation-count-853baefc6b7e8476.yaml
- releasenotes/notes/fix-gw-0c0cd70d0aa44a2e.yaml
- releasenotes/notes/maximize-to-minimize-58cd1cbd752ed382.yaml
- Fixes restructuedtext directives and slightly revised texts.
- Adds a link to CPLEX parameters in CplexSolver
> Revises reno

- requirements.txt
Related to Qiskit/qiskit-terra#6711
> Pin networkx

- .github/workflows/main.yml
> [Stable] Streamline CI (#205)

- README.md
- docs/conf.py
- docs/getting_started.rst
Also add a comment to readme  and "getting started" about no version of cplex available for python 3.9
> Add link to repo tutorial on html tutorial prolog

- qiskit_optimization/applications/max_cut.py
- qiskit_optimization/applications/tsp.py
- qiskit_optimization/problems/quadratic_program.py
- qiskit_optimization/version.py
- test/problems/test_quadratic_program.py
- tools/extract_deprecation.py
- tools/generate_spell_dict.py
> Fix lint errors

- .github/workflows/deploy-docs.yml
- .github/workflows/main.yml
- Makefile
> [Stable] Fix docs release notes search (#233)

- .github/actions/install-main-dependencies/action.yml
> Install Terra under conda environment for Windows CI

- .github/actions/install-main-dependencies/action.yml
> [Stable] Install Terra under conda for Windows CI (#242)

- test/algorithms/test_cplex_optimizer.py
- test/algorithms/test_min_eigen_optimizer.py
- test/algorithms/test_recursive_optimization.py
- test/converters/test_converters.py
Fix CPLEX parameters (number of threads and random seed) for unit tests.
Fixes #241
> Fix CPLEX parameters for unit tests

- README.md
- setup.py
Use readme as project long description in Pypi.
> Improve project setup long-description

- .github/actions/install-main-dependencies/action.yml
- .github/actions/install-optimization/action.yml
- .github/actions/run-tests/action.yml
- .github/workflows/main.yml
> Fix Miniconda CI Windows install

- .github/actions/install-main-dependencies/action.yml
- .github/actions/install-optimization/action.yml
- .github/actions/run-tests/action.yml
- .github/workflows/main.yml
> [Stable] Fix Miniconda CI Windows install (#249)

- test/algorithms/resources/op_ip3.lp
- test/algorithms/test_recursive_optimization.py
Fix CI of Windows by modifying the problem instance slightly.
> Fix test_recursive_warm_qaoa for CI of windows

- qiskit_optimization/applications/max_cut.py
Fixes `Maxcut._node_color()` for correct coloring.
`_node_color()` function in `Maxcut` was not fixed in https://github.com/Qiskit/qiskit-optimization/pull/51
> Fix _node_color in maxcut

- .github/workflows/main.yml
- .mergify.yml
- qiskit_optimization/problems/substitute_variables.py
> Fix latest pylint errors and mergify automerge

- README.md
- docs/getting_started.rst
I have fixed a few very minor grammar and formatting issues in `README.md` and `docs/getting_started.rst`.
> Fix minor grammar and formatting issues in README and getting_started

- docs/tutorials/01_quadratic_program.ipynb
I went through the first tutorial and noticed only a few formatting improvements that could be made.  I also fixed one grammar issue.
> Fix formatting & grammar in 01_quadratic_program tutorial

- qiskit_optimization/algorithms/grover_optimizer.py
Fix CI error with the recent change in the main branch of Aer https://github.com/Qiskit/qiskit-aer/pull/1388.
> Fix `GroverOptimizer` with Aer#1388

- mypy.ini
- qiskit_optimization/converters/inequality_to_equality.py
- test/applications/test_bin_packing.py
> Enable some mypy options

- qiskit_optimization/algorithms/admm_optimizer.py
- qiskit_optimization/algorithms/grover_optimizer.py
- qiskit_optimization/applications/exact_cover.py
- qiskit_optimization/applications/set_packing.py
numpy 1.22.0 released for python > 3.7 added mypy errors.
Errors fixed in this PR
> Fix mypy errors created with latest numpy

- docs/tutorials/05_admm_optimizer.ipynb
This fixes one list that was missed in #278.
See the incorrectly rendered list at https://qiskit.org/documentation/optimization/tutorials/05_admm_optimizer.html
> Fix one more list in tutorials/05_admm_optimizer.ipynb

- qiskit_optimization/__init__.py
The previous URL redirects to the https://developer.ibm.com/ front page, so I updated it to be the same URL that is listed in the qiskit-optimization README.
> Update docplex url

- docs/tutorials/01_quadratic_program.ipynb
- qiskit_optimization/algorithms/admm_optimizer.py
- qiskit_optimization/converters/quadratic_program_to_qubo.py
This includes a few changes I've been sitting on locally.  Explanations are in the commit messages.
> A couple of minor improvements to docs/comments

- requirements.txt
> Unpin networkx

- .github/actions/install-main-dependencies/action.yml
- .github/actions/install-optimization/action.yml
- .github/actions/run-tests/action.yml
- .github/workflows/main.yml
Recent CI release of Windows 2022 breaks Terra main build. Pinning to previous 2019 for now.
> Pin Windows CI version to 2019

- test/algorithms/test_recursive_optimization.py
I ran CI five times to make sure CI passes.
CI passes five times in a row. I think it's ready.
https://github.com/Qiskit/qiskit-optimization/actions/runs/1805383897/
Fixes #326
> Fix `seed_simulator` and `seed_transpiler` of `TestRecursiveMinEigenOptimizer`

- qiskit_optimization/converters/inequality_to_equality.py
- qiskit_optimization/problems/quadratic_program.py
- qiskit_optimization/problems/substitute_variables.py
- qiskit_optimization/translators/docplex_mp.py
- qiskit_optimization/translators/gurobipy.py
Fixes some sphinx markups and texts.
> Fix some API references

- docs/versionutils.py
Bengali Optimization docs are a 100% translated and proofread. Preparing to publish those docs.
This can wait till the build https://github.com/qiskit-community/qiskit-translations/actions/runs/1884635449 is successful
> Preparing to publish Bengali docs

- qiskit_optimization/runtime/vqe_client.py
- releasenotes/notes/0.3/rename-runtime-program-9b1dbb897c49f5df.yaml
This updates a docstring and release note which fell through the cracks in #246.
> Finish the `RuntimeClient` -> `Client` rename

- README.md
Refactor the example in readme to remove networkx.
Fixes #363
> Refactor the example in readme to remove networkx

- .pylintdict
- qiskit_optimization/problems/linear_constraint.py
- qiskit_optimization/problems/linear_expression.py
- qiskit_optimization/problems/quadratic_constraint.py
- qiskit_optimization/problems/quadratic_expression.py
- qiskit_optimization/problems/quadratic_objective.py
- qiskit_optimization/problems/variable.py
- qiskit_optimization/translators/prettyprint.py
- releasenotes/notes/add-repr-str-9a33af0a6ffdca6e.yaml
- test/problems/test_linear_constraint.py
- test/problems/test_linear_expression.py
- test/problems/test_quadratic_constraint.py
- test/problems/test_quadratic_expression.py
- test/problems/test_quadratic_objective.py
- test/problems/test_variable.py
- test/translators/test_prettyprint.py
This adds informative text formats to `repr` and `str` for the following classes.
- LinearConstraint
- LinearExpression
- QuadraticConstraint
- QuadraticExpression
- QuadraticObjective
- Variable
`repr` and `str` of `QuadraticProgram` and `OptimizationResult` will be updated in the next PR because they are used in tutorials and I have to update all tutorials. This PR does not affect existing tutorials.
The text of the formats is one line to be IDE friendly.
Vscode
Pycharm
I added `__repr__` and `__str__` to comply with Python's convention.
> `object.__repr__(self)`
> Called by the repr() built-in function to compute the “official” string representation of an object. If at all possible, this should look like a valid Python expression that could be used to recreate an object with the same …
> Adds informative text formats to `repr` and `str` for problem related objects (part 2/3 refactor text representation of objects)

- qiskit_optimization/translators/ising.py
- test/translators/test_ising.py
This fixes a few "typos" I noticed when looking carefully at the Ising translator and its tests.   In part, I've replaced "object function" -> "objective function" so that the language will be consistent once the QRAO prototype is contributed to Qiskit Optimization.
> Fix a few "typos" related to the Ising translator & its tests

- CONTRIBUTING.md
* Updates the link to the release planning
* removes tailing white spaces
* updates a URL to be included in <...>
> Updates the link to the release planning

- MANIFEST.in
- qiskit_optimization/py.typed
> Add py.typed marker

- .github/actions/install-main-dependencies/action.yml
> Fix CI Terra/Aer build under MacOS

- .github/workflows/main.yml
- requirements-dev.txt
- test/problems/test_quadratic_expression.py
> Pin pylint to < 2.14.0

- docs/index.rst
> Add overview to docs

- .github/workflows/main.yml
- test/algorithms/test_grover_optimizer.py
Related to Qiskit/qiskit-terra#5089
> Fix Aer Deprecate Messages

- .github/workflows/main.yml
- constraints.txt
- releasenotes/notes/drop-python3.6-support-788a41dfde01489c.yaml
- requirements-dev.txt
- requirements.txt
- setup.py
- tox.ini
> [Stable] Drop support for Python 3.6 (#290)

- .github/workflows/main.yml
Same as Qiskit/qiskit-nature#821
> Keep matplotlib installed in the CI

- .github/workflows/main.yml
- docs/apidocs/qiskit_optimization.runtime.rst
- requirements-dev.txt
> Unpin sphinx

- requirements-dev.txt
- test/test_deprecation.py
> Fixed mypy latest release errors

- qiskit_optimization/runtime/vqe_client.py
Recent Terra Merge failing CI pylint
> Call base init on VQEClient

- .github/actions/install-main-dependencies/action.yml
- .github/workflows/deploy-code.yml
- .github/workflows/deploy-docs.yml
- .github/workflows/main.yml
Following advice from Github, update actions to latest versions
> Update Github Actions versions

- qiskit_optimization/algorithms/optimization_algorithm.py
Fix an f-string typo in the constructor of `OptimizationResult`.
In `qiskit_optimization/algorithms/optimization_algorithms.py:138`, the "f" in the f-string is misplaced.
> Fix f-string error in the constructor of `OptimizationResult`

- .github/workflows/deploy-docs.yml
- .github/workflows/main.yml
> Remove sphinx_rtd_theme from CI

- requirements.txt
Latest docplex requires cplex, however cplex is an optional install in Optimization.
Pinning it for now until a decision is made.
> Pin temporarily docplex < 2.24.231

- requirements.txt
docplex 2.24.231 issue #445 is fixed by 2.24.232.
> unpin docplex

- qiskit_optimization/problems/substitute_variables.py
> Fix mypy warnings

- docs/tutorials/06_examples_max_cut_and_tsp.ipynb
> Fix removed method from networkx

- qiskit_optimization/algorithms/__init__.py
- qiskit_optimization/applications/__init__.py
Some imported items are not included in `__all__`.
This PR fixes the issue.
> Add missing items of `__all__`

- .github/actions/install-main-dependencies/action.yml
Install Aer stable instead of building Aer at CI
> Install Aer stable at CI

- docs/getting_started.rst
Related https://github.com/Qiskit/qiskit-finance/pull/247
> Improving a sentence in getting_started.rst

- docs/conf.py
See https://github.com/Qiskit/qiskit-finance/pull/244 for the motivation.
I did not test this because the docs fail to build on my M1, but as shown in https://github.com/Qiskit/qiskit-finance/pull/244, this should have no impact on the docs build.
> Remove unnecessary `html_theme_path` option

- .github/workflows/main.yml
- .pylintrc
- Makefile
- constraints.txt
- requirements-dev.txt
- setup.py
- test/translators/test_docplex_mp.py
- tools/check_copyright.py
- Updates the minimum Pylint version to 2.16.2 following Terra's PR https://github.com/Qiskit/qiskit-terra/pull/9615
- Updates pylintrc file and github action workflow using #431
- Applies black to setup.py
Co-authored-by: Manoel Marques <Manoel.Marques@ibm.com>
> Upgrade Pylint to 2.16.2

- .github/actions/run-tests/action.yml
- .github/workflows/deploy-code.yml
- .github/workflows/main.yml
Bump python version for CI check, deprecation, and coverage.
> Bump python version for CI check

- test/algorithms/legacy/__init__.py
- test/algorithms/legacy/test_min_eigen_optimizer.py
- test/algorithms/legacy/test_recursive_optimization.py
- test/algorithms/legacy/test_warm_start_qaoa.py
Update some legacy tests by changing `PendingDeprecationWarning` with `DeprecationWarning` due to deprecation opflow.
> Update legacy unit tests

- docs/tutorials/11_using_classical_optimization_solvers_and_models.ipynb
Fixes #488
I removed the reference to cplex version totally to avoid having something that would get outdated and stale again. I think the note and the links to the respective packages, for further details, suffices.
> Update tutorial 11 intro text around pip installed free solvers

- .github/workflows/main.yml
This repository was recently moved from `qiskit` to `qiskit-community`, but CI was not updated.
> Fix CI not running due to qiskit-community migration

- README.md
> Fix a link to citation file

- .github/CODEOWNERS
- .github/workflows/deploy-docs.yml
Add @dthuerck and @Sofranac-Boro as code owners.
> Add code owners

- qiskit_optimization/algorithms/optimization_algorithm.py
- test/problems/test_quadratic_program.py
#639 is missing some copyright updates. This PR fixes them.
#639 was merged because I turned CI check off by mistake. I fixed it already.
> Fix copyright

- .github/workflows/main.yml
- qiskit_optimization/algorithms/admm_optimizer.py
- qiskit_optimization/converters/linear_inequality_to_penalty.py
- releasenotes/notes/add-python313-support-e9a0326ddcb007ec.yaml
- requirements.txt
- setup.py
Fixes #659 
Need to update requirements.txt to support Python 3.13 because SciPy 1.13 is not available for Python 3.13.
If this PR is approved, I will make ubuntu-latest 3.13 required for CI.
> Add Python 3.13 support

- test/algorithms/test_admm.py
- test/algorithms/test_cobyla_optimizer.py
- test/minimum_eigensolvers/test_qaoa.py
- test/minimum_eigensolvers/test_sampling_vqe.py
- test/optimizers/test_optimizers.py
SciPy 1.16 introduces breaking changes to the behavior of COBYLA and SLSQP.
This PR updates the tests to ensure compatibility with both SciPy 1.15 and 1.16.
https://docs.scipy.org/doc/scipy/release/1.16.0-notes.html#scipy-optimize-improvements
> Updates tests to support SciPy 1.16

- qiskit_optimization/algorithms/cobyla_optimizer.py
- qiskit_optimization/algorithms/cplex_optimizer.py
- qiskit_optimization/algorithms/goemans_williamson_optimizer.py
- qiskit_optimization/algorithms/gurobi_optimizer.py
- qiskit_optimization/algorithms/slsqp_optimizer.py
- qiskit_optimization/optimizers/spsa.py
- qiskit_optimization/utils/validate_bounds.py
- qiskit_optimization/variational_algorithm.py
Fix minor typos and grammar
- an Qiskit -> a Qiskit
- it-h -> i-th
- the match the number -> match the number
- Variation -> Variational
> Fix minor typos and grammar
